name: example-wait-on
on: [push]
jobs:
  wait-on:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/wait-on
          start: npm start
          wait-on: 'http://localhost:3050'
