name: example-env
on: [push]
env:
  # this variable should always be present in specs
  CYPRESS_environmentName: staging
jobs:
  with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        with:
          working-directory: examples/env
          # additional env variables to pass to Cypress specs
          env: host=api.dev.local,port=4222
          spec: cypress/integration/spec.js

  without-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        with:
          working-directory: examples/env
          spec: cypress/integration/without-env-spec.js
