name: example-env
on: [push]
env:
  # this variable should always be present in specs
  CYPRESS_environmentName: staging
jobs:
  with-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        with:
          working-directory: examples/env
          # additional env variables to pass to Cypress specs
          environment: host=api.dev.local,port=4222
          spec: cypress/integration/spec.js

  without-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        with:
          working-directory: examples/env
          spec: cypress/integration/without-env-spec.js

  with-action-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        # more env variables via job's env block
        env:
          CYPRESS_port: 4222
          CYPRESS_host: api.dev.local
        with:
          working-directory: examples/env
          spec: cypress/integration/spec.js

  combined-env:
    # 1st var comes from workflow's env
    # 2nd from "env" block
    # 3rd comes via action's "with: env:" block
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run with env
        uses: ./
        env:
          DEBUG: cypress:server:args
          CYPRESS_port: 4222
        with:
          environment: host=api.dev.local
          working-directory: examples/env
          spec: cypress/integration/spec.js
