name: example-basic
on: [push]
jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/cypress@v1
        uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: examples/basic

      # store screenshot captured during the test
      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-electron
          path: examples/basic/cypress/screenshots

      - name: Chrome
        uses: ./
        with:
          working-directory: examples/basic
          browser: chrome

        - uses: actions/upload-artifact@v1
          with:
            name: screenshots-in-chrome
            path: examples/basic/cypress/screenshots

  basic-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/basic
