name: example-chrome
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Electron
        uses: ./
        with:
          working-directory: examples/chrome

      # store screenshot captured during the test
      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-electron
          path: examples/chrome/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome

      - name: Chrome
        uses: ./
        with:
          working-directory: examples/chrome
          browser: chrome

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-chrome
          path: examples/chrome/cypress/screenshots

      - uses: actions/upload-artifact@v1
        with:
          name: video-in-chrome
          path: examples/chrome/cypress/video

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome

      - name: Chrome headless
        uses: ./
        with:
          working-directory: examples/chrome
          browser: chrome
          headless: true

      - uses: actions/upload-artifact@v1
        with:
          name: screenshots-in-headless-chrome
          path: examples/chrome/cypress/screenshots

      - uses: actions/upload-artifact@v1
        with:
          name: video-in-headless-chrome
          path: examples/chrome/cypress/video

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/chrome
